clc;

data = importdata('in.dta');

Xin = data(:,1:2);
yin = data(:,3);

X = Xin;
y = yin;

X = [   ones(size(X,1), 1) ...
        X(:,1) ...
        X(:,2) ...
        X(:,1).^2 ...
        X(:,2).^2 ...
        X(:,1).*X(:,2) ...
        abs(X(:,1)-X(:,2)) ...
        abs(X(:,1)+X(:,2))];
        
w = pinv(X) * y; 

h = zeros(size(X,1),1);
for b = 1 : size(X,1)  
    
    h(b) = sign(    w(1) * X(b,1) + ...
                    w(2) * X(b,2) + ... 
                    w(3) * X(b,3) + ... 
                    w(4) * X(b,4) + ... 
                    w(5) * X(b,5) + ... 
                    w(6) * X(b,6) + ... 
                    w(7) * X(b,7) + ... 
                    w(8) * X(b,8) ...
                );

end

ein = (sum(abs(y - h))/2) / size(X,1);

fprintf('Ein(g): %f: \n', ein);

data = importdata('out.dta');

Xout = data(:,1:2);
yout = data(:,3);

X = Xout;
y = yout;

X = [   ones(size(X,1), 1) ...
        X(:,1) ...
        X(:,2) ...
        X(:,1).^2 ...
        X(:,2).^2 ...
        X(:,1).*X(:,2) ...
        abs(X(:,1)-X(:,2)) ...
        abs(X(:,1)+X(:,2))];

h = zeros(size(X,1),1);
for b = 1 : size(X,1)  
    
    h(b) = sign(    w(1) * X(b,1) + ...
                    w(2) * X(b,2) + ... 
                    w(3) * X(b,3) + ... 
                    w(4) * X(b,4) + ... 
                    w(5) * X(b,5) + ... 
                    w(6) * X(b,6) + ... 
                    w(7) * X(b,7) + ... 
                    w(8) * X(b,8) ...
                );

end

eout = (sum(abs(y - h))/2) / size(X,1);

fprintf('Eout(g): %f: \n', eout);